version: "3.3"
services:
  db:
    container_name: apu-postgraphile-db
    restart: always
    image: apu-postgraphile-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 5432
  graphql:
    container_name: apu-postgraphile-graphql
    restart: always
    image: apu-postgraphile-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5433:5433
    command:
      [
        "--connection",
        "${DATABASE_URL}",
        "--port",
        "5433",
        "--schema",
        "mygraphile",
        "--append-plugins",
        "@graphile/pg-aggregates",
      ]

networks:
  network:

volumes:
  db:
